"use client";

import { CheckCircle } from "lucide-react";

const includedItems = [
  "Cover page with brand colors",
  "Table of contents for easy navigation",
  "Executive summary",
  "Functional requirements with priorities",
  "Non-functional requirements",
  "UI component documentation",
  "Technical requirements with options",
  "Success metrics and KPIs",
  "Timeline and milestones",
  "Risk assessment",
];

export default function PDFOutput() {
  return (
    <section className="section bg-near-black/50">
      <div className="container-custom">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center max-w-5xl mx-auto">
          {/* Left - Content */}
          <div>
            <h2 className="text-h1 mb-4">Professional PDF Output</h2>
            <p className="text-text-secondary mb-8">
              Every PRD includes comprehensive documentation following
              industry standard practices, ready to share with your team or clients.
            </p>

            <ul className="space-y-3">
              {includedItems.map((item) => (
                <li key={item} className="flex items-start gap-3">
                  <CheckCircle className="h-5 w-5 text-success flex-shrink-0 mt-0.5" />
                  <span className="text-sm text-white/80">{item}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Right - Preview mockup */}
          <div className="relative">
            <div className="card p-6 bg-white text-gray-800">
              <div className="border-b pb-4 mb-4">
                <div className="text-xs text-gray-500 mb-1">Brand Style Guide</div>
                <div className="text-lg font-bold">Version 1.0 | Generated Today</div>
              </div>

              <div className="space-y-4 text-sm">
                <div>
                  <div className="font-semibold mb-2">Color Palette</div>
                  <div className="flex gap-2">
                    <div className="w-8 h-8 bg-gray-800 rounded"></div>
                    <div className="w-8 h-8 bg-teal rounded"></div>
                    <div className="w-8 h-8 bg-success rounded"></div>
                    <div className="w-8 h-8 bg-amber-400 rounded"></div>
                  </div>
                </div>

                <div>
                  <div className="font-semibold mb-2">Typography</div>
                  <div className="text-xs text-gray-500">Primary Font: system-ui</div>
                  <div className="text-xs text-gray-500">Secondary Font: ui-monospace</div>
                </div>
              </div>

              <div className="mt-4 pt-4 border-t flex items-center justify-between text-xs text-gray-400">
                <span>Page 1 of 19</span>
                <span>Generated by PRD Builder</span>
              </div>
            </div>

            {/* Decorative background cards */}
            <div className="absolute -z-10 top-4 -right-4 w-full h-full card bg-white/5"></div>
            <div className="absolute -z-20 top-8 -right-8 w-full h-full card bg-white/[0.02]"></div>
          </div>
        </div>
      </div>
    </section>
  );
}
